version: "3.7"

services:
  servicio-apache:
    image: php:apache-bullseye
    ports:
      - "8080:80"
    volumes:
      - C:\Users\angel\OneDrive\Escritorio\swarm:/var/www/html/  # Monta el archivo PHP
    command: >
      sh -c "
        docker-php-ext-install mysqli && 
        docker-php-ext-enable mysqli && 
        apache2-foreground
      "
    depends_on:
      - mysql  
    deploy:
      replicas: 3
    networks:
      - networkName

  servicio-nodejs:
    image: node:14
    ports:
      - "8090:3000"
    volumes:
      - C:\Users\angel\OneDrive\Escritorio\swarm:/app
    depends_on:
      - mysqlito
    deploy:
      replicas: 3
    command: >
      bash -c "echo 'const http = require(\"http\");
      http.createServer((req, res) => res.send(\"Hola mundo\")).listen(3000);'
      > index.js && node index.js"
    networks:
      - networkName

  mysqlito:
    image: mysql:debian
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - C:\Users\angel\OneDrive\Escritorio\swarm\mysql/datos.sql:/docker-entrypoint-initdb.d/datos.sql  # Monta el archivo SQL al directorio de inicialización de MySQL
      - C:\Users\angel\OneDrive\Escritorio\swarm\mysql-datos:/var/lib/mysql
    networks:
      - networkName

networks:
  networkName:
